apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-python-app
  labels:
    app: demo-python-app
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo-python-app
  template:
    metadata:
      labels:
        app: demo-python-app
    spec:
      containers:
        - name: demo-python-app
          image: docker-repo.sk-devops.com/docker-sk-devops:sk:latest
          ports:
            - containerPort: 5000
      imagePullSecrets:
          -name : regcred
