apiVersion: v1
kind: Service
metadata:
  name: demp-python-app-service
  namespace: default
  labels:
    app: demo-python-app
spec:
  selector:
    app: demo-python-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: ClusterIP
